stages:
  - lint
  - tests
  - build

variables:
  CARGO_HOME: "$CI_PROJECT_DIR/.cargo"

eslint:
  stage: lint
  image: denoland/deno:latest
  cache:
    key:
      files:
        - deno.lock
    paths:
      - .deno/
  script:
    - deno lint

clippy:
  stage: lint
  image: rust:1.97.1
  cache:
    key:
      files:
        - src-tauri/Cargo.lock
    paths:
      - .cargo/registry
      - src-tauri/target/
  before_script:
    - rustup component add clippy
  script:
    - cd src-tauri
    - cargo clippy --all-targets --all-features -- -D warnings