stages:
  - lint
  - tests
  - build

eslint:
  stage: lint
  image: node:24-alpine
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
      - .npm/
  before_script:
    - npm install --save-dev eslint @eslint/js typescript typescript-eslint eslint-plugin-vue vue-eslint-parser globals
  script:
    - npx eslint .

clippy:
  stage: lint
  image: rust:1.96.0
  cache:
    key:
      files:
        - Cargo.lock
    paths:
      - .cargo/registry
      - target/
  script:
      - rustup component add clippy
      - cd ./src-tauri
      - cargo clippy --all-targets --all-features
