ARG RUST_IMAGE_DIGEST
FROM rust@${RUST_IMAGE_DIGEST}

ARG GITLAB_APT_PACKAGES
ARG DEBIAN_SNAPSHOT_BASE_URL
ARG APT_SNAPSHOT_TIMESTAMP
ARG DENO_VERSION

RUN set -eux; \
    codename="$(. /etc/os-release && echo "$VERSION_CODENAME")"; \
    echo "deb [check-valid-until=no] ${DEBIAN_SNAPSHOT_BASE_URL}/${APT_SNAPSHOT_TIMESTAMP}/ ${codename} main" > /etc/apt/sources.list; \
    apt-get -o Acquire::Check-Valid-Until=false update; \
    apt-get install -y --no-install-recommends ${GITLAB_APT_PACKAGES}; \
    curl -fsSL https://deno.land/install.sh | DENO_INSTALL=/usr/local sh -s v${DENO_VERSION}; \
    rm -rf /var/lib/apt/lists/*